#!/bin/bash

if [ $# -lt 1 ]; then
    echo ""
    echo "[DESCRIPTION]"
    echo "Put device into kDFU mode using pwnediBSS"
    echo ""
    echo "[USAGE]"
    echo "./enterkdfu <device IP>"
    echo ""
    echo "[EXAMPLE]"
    echo "./enterkdfu 192.168.1.88"
    echo ""
    exit
fi
if [ $# -gt 1 ]; then
    echo "[ERROR] Too many arguments"
    exit
fi

ip=$1

if [ $OSTYPE = msys ]; then
    echo "Windows Detected"
    path="/c/Users/`whoami`/Downloads"
    platform="win"
elif [[ $OSTYPE == "darwin"* ]]; then
    echo "macOS Detected"
    path="/Users/`whoami`/Downloads"
    platform="macos"
else
    echo "Not supported"
    exit
fi

cd "$path/blobs/odysseus-0.999.0/$platform"

if [ -e "pwnediBSS" ]; then
	echo ""
	echo "Found pwnediBSS"
else
	echo ""
	echo "Did not find pwnediBSS, have you ran ./patchipsw?"
	exit 1	
fi
echo ""
echo "Attempting to enter kDFU"
echo ""
echo "If asked, type yes, then the default password is \"alpine\""
echo ""
echo "WHEN YOUR DEVICE TURNS OFF, (RE)PLUG YOUR DEVICE INTO YOUR COMPUTER, PRESS CONTROL+C, AND PROCEED TO \"./dumpblobs\". IGNORE ITUNES"
echo ""
./sshtool -k ../kloader -b pwnediBSS -p 22 $ip
echo ""
echo "IF YOUR DEVICE DID NOT TURN OFF, SEE TROUBLESHOOTING"
echo ""

