#!/bin/bash

if [ "`whoami`" = root ]; then
  echo "Please do not run this as the root user"
  exit
fi

if [ $# -lt 2 ]; then
    echo ""
    echo "[DESCRIPTION]"
    echo "Downloads correct IPSW's, Odysseus & FirmwareBundels"
    echo ""
    echo "[USAGE]"
    echo "./prepare <device model> <ios version>"
    echo ""
    echo "[EXAMPLES]"
    echo "./prepare iPad3,5 6.1.2"
    echo "./prepare iPod5,1 9.1"
    echo "./prepare iPhone4,1 8.4.1"
    echo ""
    exit
fi
if [ $# -gt 2 ]; then
    echo "[ERROR] Too many arguments"
    exit
fi

if [ $OSTYPE = msys ]; then
	echo "Windows Detected"
	path="/c/Users/`whoami`/Downloads"
	platform="win"
elif [[ $OSTYPE == "darwin"* ]]; then
	echo "macOS Detected"
	path="/Users/`whoami`/Downloads"
	platform="macos"
else
	echo "Not supported"
	exit
fi

if ! [[ `curl -sS "https://rossdarker.github.io/o"` && `curl -sS "https://api.ipsw.me/v4/"` ]] ; then
	echo "Could not connect to Github or IPSW.me - See Troubleshooting"
	exit
fi

if [ -e "$path/blobs" ]; then
  rm -r "$path/blobs"
fi

mkdir "$path/blobs"
cd "$path/blobs"

model=$1
ios=$2

curl -sS -o defaultbdids "https://rossdarker.github.io/o/defaultbdids"
buildid=`cat defaultbdids | grep $model | cut -d \; -f 2`
echo $buildid > extbdid

echo "Calculating Build ID for iOS $ios"

echo -e "Please wait...\n"

cutios=`echo $ios | cut -d . -f 1`

mainbdid=`curl -sS "https://api.ipsw.me/v4/device/$model?type=ipsw" | tr '{' '\n' | grep "version\":\"$ios\"" | cut -d \" -f 12`


if [[ $mainbdid == *"
"* ]]; then
	echo -e "Possible Build IDs: \n$mainbdid\n"
	echo "Multiple builds of iOS $ios may exist, please enter the Build ID for the version you are on, exactly as one appears from the list above (case sensitive):"
	read newmainbdid
	echo ""
	if [[ $mainbdid == *$newmainbdid* ]]; then
		mainbdid=$newmainbdid
	else
		echo "Check that you typed in the Build ID correctly!"
		exit
	fi
fi

ipswurl="https://api.ipsw.me/v4/ipsw/download/$model/$mainbdid"

if [ "$mainbdid" = "" ]; then
	curl -sS -o exceptions "https://rossdarker.github.io/o/exceptions"
	mainbdid=`cat exceptions | grep "$model;$ios" | cut -d \; -f 3`
	ipswurl=`cat exceptions | grep "$model;$ios" | cut -d \; -f 4`
fi

if [ "$mainbdid" = "" ]; then
	echo "Could not find iOS $ios for $model!"
	exit
fi

echo $mainbdid > mainbdid
echo "Build ID for extraction iOS: $buildid"
echo "Build ID for current iOS: $mainbdid"
echo -e "Model: $model\n"

echo "Downloading extraction IPSW..."
curl -# -k -o "$model_$buildid.ipsw" -L "https://api.ipsw.me/v4/ipsw/download/$model/$buildid"

if [ $buildid = $mainbdid ]; then
	echo "Build IDs are the same"
else
	echo "Build IDs are different, downloading IPSW for iOS $ios as well..."
	curl -# -k -o "$model_$mainbdid.ipsw" -L "$ipswurl"
fi
echo "Downloading Odysseus & FirmwareBundles"
curl -# -o odysseus.zip https://rossdarker.github.io/o/odysseus-0.999.zip
unzip -qq odysseus.zip
rm odysseus.zip
curl -# -o FirmwareBundles.zip https://rossdarker.github.io/o/FirmwareBundles.zip
unzip -qq FirmwareBundles.zip
rm FirmwareBundles.zip
rm -r odysseus-0.999.0/macos/FirmwareBundles
mv FirmwareBundles odysseus-0.999.0/macos/

if [ $cutios = "10" ]; then
	echo "Downloading kloader for iOS 10"
	curl -# -o kloader https://rossdarker.github.io/o/kloaders/10/kloader
	rm odysseus-0.999.0/kloader
	chmod +x kloader
	mv kloader  odysseus-0.999.0/
fi
if [ $cutios = "5" ]; then
	echo "Downloading kloader for iOS 5"
	curl -# -o kloader https://rossdarker.github.io/o/kloaders/5/kloader
	rm odysseus-0.999.0/kloader
	chmod +x kloader
	mv kloader  odysseus-0.999.0/
fi

if [ $platform = "win" ]; then
	echo "Downloading xpwn for Windows"
	curl -# -o xpwn_win.zip https://rossdarker.github.io/o/xpwn_win.zip
	unzip -qq xpwn_win.zip -d odysseus-0.999.0/
	rm xpwn_win.zip
	mv odysseus-0.999.0/macos/FirmwareBundles/ odysseus-0.999.0/win/FirmwareBundles
fi

echo ""
echo "Done"