#!/bin/bash

if [ $# -lt 2 ]; then
    echo ""
    echo "[DESCRIPTION]"
    echo "Sends pwned iBEC to device in kDFU mode and then dumps onboard blobs"
    echo ""
    echo "[USAGE]"
    echo "./dumpblobs <device model> <ios version>"
    echo ""
    echo "[EXAMPLES]"
    echo "./dumpblobs iPad3,5 7.1.2"
    echo "./dumpblobs iPod5,1 9.1"
    echo "./dumpblobs iPhone4,1 6.0.1"
    echo ""
    exit
fi
if [ $# -gt 2 ]; then
    echo "[ERROR] Too many arguments"
    exit
fi

if [ $1 = "iPhone4,1" ]; then
    buildid="10B329"
fi
if [ $1 = "iPhone5,1" ]; then
    buildid="10B329"
fi
if [ $1 = "iPhone5,2" ]; then
    buildid="10B329"
fi
if [ $1 = "iPhone5,3" ]; then
    buildid="11B511"
fi
if [ $1 = "iPhone5,4" ]; then
    buildid="11B651"
fi
if [ $1 = "iPod5,1" ]; then
    buildid="10B329"
fi
if [ $1 = "iPad2,1" ]; then
    buildid="10B329"
fi
if [ $1 = "iPad2,2" ]; then
    buildid="11D257"
fi
if [ $1 = "iPad2,3" ]; then
    buildid="12H321"
fi
if [ $1 = "iPad2,4" ]; then
    buildid="10B329"
fi
if [ $1 = "iPad2,5" ]; then
    buildid="10B329"
fi
if [ $1 = "iPad2,6" ]; then
    buildid="12H321"
fi
if [ $1 = "iPad2,7" ]; then
    buildid="12H321"
fi
if [ $1 = "iPad3,1" ]; then
    buildid="10B146"
fi
if [ $1 = "iPad3,2" ]; then
    buildid="12H321"
fi
if [ $1 = "iPad3,3" ]; then
    buildid="10B329"
fi
if [ $1 = "iPad3,4" ]; then
    buildid="10B329"
fi
if [ $1 = "iPad3,5" ]; then
    buildid="12H321"
fi
if [ $1 = "iPad3,6" ]; then
    buildid="10B329"
fi

model=$1
ios=$2
echo "Build ID: $buildid"
echo "iOS Version: $2"
echo "Model: $model"

cd ~/Downloads/blobs/odysseus-0.999.0/macos/

echo "Will attempt to send iBEC"
echo ""
./irecovery -f pwnediBEC
echo "Continuing in 10 seconds..."
echo "******"
echo "UNPLUG THEN RECONNECT DEVICE TO COMPUTER NOW"
echo "******"
sleep 10
echo "Sending commands to device"
(echo -e "/send ../payload\ngo blobs\n/exit") | ./irecovery -s
echo ""
sleep 1
./irecovery -g myblob.dump
echo "Rebooting device"
sleep 1
./irecovery -c reboot 
echo ""
sleep 1
./ticket myblob.dump myblob.plist current.ipsw -z
./validate myblob.plist current.ipsw -z
ECID=`./ticket myblob.dump myblob2.plist current.ipsw -z | grep ECID | cut -d = -f 2`
sleep 1
if [ -e "myblob.plist" ]; then
	mv myblob.plist "$ECID-$model-$ios.shsh"
	mv "$ECID-$model-$ios.shsh" ~/Desktop/
	echo "BLOBS SAVED AS: $ECID-$model-$ios.shsh"
	echo "Blobs were successfully saved! This file has been moved onto your Desktop!"
else
	echo "Did NOT succeed. Try again, or try on a version of Mac OS X that is Yosemite or earlier (10.10 or earlier)"
	
fi 


