#!/bin/bash

if [ $# -lt 2 ]; then
    echo ""
    echo "[DESCRIPTION]"
    echo "Extracts baseband, builds custom IPSW, and extracts iBEC & iBSS"
    echo ""
    echo "[USAGE]"
    echo "./patchipsw <device model> <device IP>"
    echo ""
    echo "[EXAMPLES]"
    echo "./patchipsw iPad3,5 192.168.1.88"
    echo "./patchipsw iPod5,1 192.168.1.201"
    echo "./patchipsw iPhone4,1 192.168.1.14"
    echo ""
    exit
fi
if [ $# -gt 2 ]; then
    echo "[ERROR] Too many arguments"
    exit
fi

cd ~/Downloads/blobs

if [ $1 = "iPhone4,1" ]; then
    buildid="10B329"
fi
if [ $1 = "iPhone5,1" ]; then
    buildid="10B329"
fi
if [ $1 = "iPhone5,2" ]; then
    buildid="10B329"
fi
if [ $1 = "iPhone5,3" ]; then
    buildid="11B511"
fi
if [ $1 = "iPhone5,4" ]; then
    buildid="11B651"
fi
if [ $1 = "iPod5,1" ]; then
    buildid="10B329"
fi
if [ $1 = "iPad2,1" ]; then
    buildid="10B329"
fi
if [ $1 = "iPad2,2" ]; then
    buildid="11D257"
fi
if [ $1 = "iPad2,3" ]; then
    buildid="12H321"
fi
if [ $1 = "iPad2,4" ]; then
    buildid="10B329"
fi
if [ $1 = "iPad2,5" ]; then
    buildid="10B329"
fi
if [ $1 = "iPad2,6" ]; then
    buildid="12H321"
fi
if [ $1 = "iPad2,7" ]; then
    buildid="12H321"
fi
if [ $1 = "iPad3,1" ]; then
    buildid="10B146"
fi
if [ $1 = "iPad3,2" ]; then
    buildid="12H321"
fi
if [ $1 = "iPad3,3" ]; then
    buildid="10B329"
fi
if [ $1 = "iPad3,4" ]; then
    buildid="10B329"
fi
if [ $1 = "iPad3,5" ]; then
    buildid="12H321"
fi
if [ $1 = "iPad3,6" ]; then
    buildid="10B329"
fi

model=$1
ip=$2
mainbdid=`cat mainbdid`
echo "Build ID: $buildid"
echo "Model: $model"
echo "Devcice IP: $ip"

mv "$buildid.ipsw" odysseus-0.999.0/macos/downloaded.ipsw
if [ ! $buildid = $mainbdid ]; then
	mv "$mainbdid.ipsw" odysseus-0.999.0/macos/current.ipsw
fi

cd ~/Downloads/blobs/odysseus-0.999.0/macos/
if [ $2 != "skip" ]; then
echo "Will attempt to extract baseband from device"
echo ""
echo "If asked, type yes, then the default password is \"alpine\""
echo ""
./sshtool -s baseband.tar -p 22 $ip
echo ""
if [ -e "baseband.tar" ]; then
	echo "Successfully received baseband from device, if it has one"
else
	echo "Couldn't connect to device, install OpenSSH from Cydia, or run: rm ~/.ssh/known_hosts, then try again."
	exit
fi
fi

echo ""
echo "Patching IPSW"

if [ $2 != "skip" ]; then
	./ipsw downloaded.ipsw custom.ipsw -memory baseband.tar
else
	./ipsw downloaded.ipsw custom.ipsw -memory
fi

if [ -e "custom.ipsw" ]; then
	echo ""
	echo "Successfully created custom IPSW"
else
	echo ""
	echo "Did not succeed, trying without baseband.tar..."
	./ipsw downloaded.ipsw custom.ipsw -memory
fi
echo ""


echo "Extracting pwned iBSS..."
./xpwntool `unzip -j custom.ipsw 'Firmware/dfu/iBSS*' | awk '/inflating/{print $2}'` pwnediBSS
echo "Extracting pwned iBEC..."
mv `unzip -j custom.ipsw 'Firmware/dfu/iBEC*' | awk '/inflating/{print $2}'` pwnediBEC
if [ $buildid = $mainbdid ]; then
	mv "downloaded.ipsw" "current.ipsw"
fi
echo "Done"
