#!/bin/bash

if [ "`whoami`" = root ]; then
  echo "Please do not run this as the root user"
  exit
fi

if [ $# -lt 2 ]; then
    echo ""
    echo "[DESCRIPTION]"
    echo "Downloads correct IPSW's, Odysseus & FirmwareBundels"
    echo ""
    echo "[USAGE]"
    echo "./prepare <device model> <ios version>"
    echo ""
    echo "[EXAMPLES]"
    echo "./prepare iPad3,5 6.1.2"
    echo "./prepare iPod5,1 9.1"
    echo "./prepare iPhone4,1 8.4.1"
    echo ""
    exit
fi
if [ $# -gt 2 ]; then
    echo "[ERROR] Too many arguments"
    exit
fi

if [ -e "/Users/`whoami`/Downloads/blobs" ]; then
  rm -r ~/Downloads/blobs
fi

mkdir ~/Downloads/blobs
cd ~/Downloads/blobs

if [ $1 = "iPhone4,1" ]; then
    buildid="10B329"
fi
if [ $1 = "iPhone5,1" ]; then
    buildid="10B329"
fi
if [ $1 = "iPhone5,2" ]; then
    buildid="10B329"
fi
if [ $1 = "iPhone5,3" ]; then
    buildid="11B511"
fi
if [ $1 = "iPhone5,4" ]; then
    buildid="11B651"
fi
if [ $1 = "iPod5,1" ]; then
    buildid="10B329"
fi
if [ $1 = "iPad2,1" ]; then
    buildid="10B329"
fi
if [ $1 = "iPad2,2" ]; then
    buildid="11D257"
fi
if [ $1 = "iPad2,3" ]; then
    buildid="12H321"
fi
if [ $1 = "iPad2,4" ]; then
    buildid="10B329"
fi
if [ $1 = "iPad2,5" ]; then
    buildid="10B329"
fi
if [ $1 = "iPad2,6" ]; then
    buildid="12H321"
fi
if [ $1 = "iPad2,7" ]; then
    buildid="12H321"
fi
if [ $1 = "iPad3,1" ]; then
    buildid="10B146"
fi
if [ $1 = "iPad3,2" ]; then
    buildid="12H321"
fi
if [ $1 = "iPad3,3" ]; then
    buildid="10B329"
fi
if [ $1 = "iPad3,4" ]; then
    buildid="10B329"
fi
if [ $1 = "iPad3,5" ]; then
    buildid="12H321"
fi
if [ $1 = "iPad3,6" ]; then
    buildid="10B329"
fi

model=$1
ios=$2
echo "Calculating BuildID for iOS $ios"

echo "Please wait..."

curl -# -k -o "firmware" -L https://api.ipsw.me/v2.1/firmwares.json/

cutios=`echo $ios | cut -d . -f 1`

if [ "$cutios" == "10" ]; then
	if [[ $model = *"iPad"* ]]; then
		cat firmware | grep "$ios"_"" | grep "iPad_32bit" | grep "filename" | cut -d "_" -f 4
		mainbdid=`cat firmware | grep "$ios"_"" | grep "iPad_32bit" | grep "filename" | cut -d "_" -f 4`
	fi
	if [[ $model = *"iPhone"* ]]; then
		cat firmware | grep "$ios"_"" | grep "iPhone_4.0_32bit" | grep "filename" | cut -d "_" -f 5
		mainbdid=`cat firmware | grep "$ios"_"" | grep "iPhone_4.0_32bit" | grep "filename" | cut -d "_" -f 5`
	fi
else
	mainbdid=`cat firmware | grep "$model"_"$ios"_"" | grep "http" | cut -d _ -f 3`
	cat firmware | grep "$model"_"$ios"_"" | grep "http" | cut -d _ -f 3
fi


if [[ $mainbdid == *"
"* ]]; then
	echo "Multiple builds of iOS $ios may exist, please enter the Build ID for the version you are on, exactly as one appears from the list above (case sensitive) :"
	read newmainbdid
	if [[ $mainbdid == *$newmainbdid* ]]; then
		mainbdid=$newmainbdid
	else
		echo "Check that you typed in the Build ID correctly!"
		exit
	fi
fi

if [ "$mainbdid" = "" ]; then
	echo "iOS $ios does not exist for $model!"
	exit
fi

echo $mainbdid > mainbdid
echo "Build ID for extraction iOS: $buildid"
echo "Build ID for current iOS: $mainbdid"
echo "Model: $model"

echo "Downloading correct IPSW"
curl -# -k -o "$model_$buildid.ipsw" -L "https://api.ipsw.me/v4/ipsw/download/$model/$buildid"
echo "Downloaded IPSW for extraction"
if [ $buildid = $mainbdid ]; then
	echo "BuildIDs are the same"
else
	echo "BuildIDs are different, downloading IPSW for iOS $ios as well"
	curl -# -k -o "$model_$mainbdid.ipsw" -L "https://api.ipsw.me/v4/ipsw/download/$model/$mainbdid"
fi
echo "Downloading Odysseus & FirmwareBundles"
curl -# -o odysseus.zip https://dayt0n.com/odysseus/odysseus-0.999.zip
unzip -qq odysseus.zip
rm odysseus.zip
curl -# -o FirmwareBundles.zip https://rossdarker.github.io/o/FirmwareBundles.zip
unzip -qq FirmwareBundles.zip
rm FirmwareBundles.zip
rm -r odysseus-0.999.0/macos/FirmwareBundles
mv FirmwareBundles odysseus-0.999.0/macos/

if [ $cutios = "10" ]; then
	echo "Downloading kloader for iOS 10"
	curl -# -o kloader https://rossdarker.github.io/o/kloaders/10/kloader
	rm odysseus-0.999.0/kloader
	chmod +x kloader
	mv kloader  odysseus-0.999.0/
fi
if [ $cutios = "5" ]; then
	echo "Downloading kloader for iOS 5"
	curl -# -o kloader https://rossdarker.github.io/o/kloaders/5/kloader
	rm odysseus-0.999.0/kloader
	chmod +x kloader
	mv kloader  odysseus-0.999.0/
fi

echo ""
echo "Done"
